<?php
$z[0]=Array("global","",23,48);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("field","",503,526);
$z[1][4]['name']="id";
$z[2]=Array("global","",958,990);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1149,1181);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1338,1370);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("php","\r\n								for (\$i = 1; \$i < 12; \$i++)\r\n								{\r\n                                    \$isecheck = (\$i == 1) ? 'checked=\"1\" ' : '';\r\n								    echo '<li><input type=\"radio\" name=\"face\" value=\"1\" '.\$isecheck.'/><img src=\"'.\$cfg_templets_skin.'/images/mood/ico-mood-'.\$i.'.gif\" /></li>';\r\n								}\r\n								",1592,1920);
$z[6]=Array("php","\r\n								if(\$cfg_mb_open=='Y') {\r\n									echo '用户名:<input type=\"text\" name=\"username\" size=\"16\" class=\"ipt-txt\" style=\"text-transform: uppercase;\"/>';\r\n								}\r\n								",2236,2434);
$z[7]=Array("php","\r\n								if(preg_match(\"/4/\",\$safe_gdopen)){\r\n								echo '验证码:<input type=\"text\" name=\"validate\" size=\"4\" class=\"ipt-txt\" style=\"text-transform:uppercase;\"/><img src= \"'.\$cfg_cmspath.'/include/vdimgck.php\" id=\"validateimg\" style=\"cursor:pointer\" onclick=\"this.src=this.src+\\'?\\'\" title=\"点击我更换图片\" alt=\"点击我更换图片\" />';\r\n								 }\r\n                                ",2468,2869);
$z[8]=Array("php","\r\n								if(\$cfg_mb_open=='Y') {\r\n              		echo '<script language=\"javascript\" type=\"text/javascript\">CheckLogin();</script>';\r\n              	}\r\n							",3028,3210);
$z[9]=Array("field","",3599,3626);
$z[9][4]['name']="phpurl";
$z[10]=Array("field","",3644,3660);
$z[10][4]['name']="id";
$z[11]=Array("global","",4211,4236);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("global","",4376,4402);
$z[12][4]['name']="cfg_phpurl";
$z[13]=Array("field","",4440,4456);
$z[13][4]['name']="id";
$z[14]=Array("global","",4796,4821);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("global","",5709,5737);
$z[15][4]['name']="cfg_soft_lang";
$z[16]=Array("field","",5803,5819);
$z[16][4]['name']="id";
$z[17]=Array("global","",6162,6187);
$z[17][4]['name']="cfg_phpurl";
$z[18]=Array("global","",6326,6351);
$z[18][4]['name']="cfg_cmsurl";

?>