<?php
$z[0]=Array("global","",185,213);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",226,245);
$z[1][4]['name']="title";
$z[2]=Array("global","",246,272);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",313,342);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",382,440);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",487,519);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",580,612);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("channel","\r\n<li><a href='[field:typelink/]' target=\"_blank\" >[field:typename/]</a></li>\r\n",957,1106);
$z[7][4]['row']="6";
$z[7][4]['type']="top";
$z[7][4]['typeid']="1,2,3,4,5,6";
$z[8]=Array("global","",1243,1275);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("arclist","\r\n  <LI><a href=\"[field:arcurl/]\" >[field:title/]</a> <SPAN>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</SPAN></LI>",1377,1571);
$z[9][4]['typeid']="1,2,3,4,5,6,7";
$z[9][4]['row']="30";
$z[9][4]['titlelen']="28";
$z[10]=Array("pagelist","",1608,1674);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("artlist","<DD><a href=\"[field:arcurl/]\">[field:title/]</a> </DD>",1992,2099);
$z[11][4]['row']="10";
$z[11][4]['type']="commend";
$z[12]=Array("arclist","<DD><a href=\"[field:arcurl/]\">[field:title/]</a> </DD>",2149,2253);
$z[12][4]['row']="10";
$z[12][4]['orderby']="click";

?>