document.writeln(" <h3>—关于我们—</h3>");
document.writeln("    <P style=\"line-height:17px; font-size:13px;\">");
document.writeln("    内江市投壶网络科技有限公司 为休闲游戏爱好者提供最优质的游戏平台和最贴心的服务,努力发展成为最受欢迎的网上休闲游戏网络公司。 公司研发方向是立足于全国市场的潮流变化之上，以开发出适合玩家需求的游戏平台。我们的经营理念是通过向我们的顾客提供最佳的线上休闲娱乐体验来发展我们的业务。</p>");
document.writeln("   <h3>—我们的特色—</h3>");
document.writeln("   <P style=\"line-height:17px; font-size:13px;\">");
document.writeln("    优质的客户服务 我们的客户服务部将为您提供365天*24小时不间断的友善和专业客户咨询服务。");
document.writeln("    </p>");
document.writeln("<h3>—我们的声明—</h3>");
document.writeln("<P style=\"line-height:17px; font-size:13px;\">");
document.writeln("    具备安全及隐私性的环境 我们提供安全端口（SSL 128 bit encryption Standard）并存放在公众无法进入的保密环境之下。所有数据的内部出入都受到限制及严密的监控，并保证决不将您的资料出售或透漏给第三方。 欺诈行为与安全性 为了维护一个良好的游戏平台环境，以公平有效为您服务，每一个用户只能拥有相对应的唯一的账户，为了您账户资金的安全请您注册时用的姓名必须与银行卡姓名一致，我们将会通过进行不定时的安全检查来维护系统的完整性及公平性。如果我们发现任何用户有欺诈行为，我们将立即关闭及取消他的账户。根据本公司的相关章程条例，任何通过欺诈行为而获取的资金将有可能被没收和被追回,绝对是玩家最明智最受益的选择！ ");
document.writeln("    </p>");
document.writeln("<h3>—联系我们—</h3>");
document.writeln("<P style=\"line-height:17px; font-size:13px;\">");
document.writeln("    联系地址：内江市东兴区汗安大道 <br/>");
document.writeln("    联系电话:0832-98867890 ");
document.writeln("    </p>");