<?php  exit();
/*
Page: /qipai/dede/sys_data.php
Error: 无法使用数据库
*/
?>
<?php  exit();
/*
Page: /qipai/dede/index.php
Error: 无法使用数据库
*/
?>
<?php  exit();
/*
Page: /qipai/dede/login.php?gotopage=%2Fqipai%2Fdede%2Findex.php
Error: 无法使用数据库
*/
?>
<?php  exit();
/*
Page: /qipai/dede/login.php?dopost=showad
Error: 无法使用数据库
*/
?>
<?php  exit();
/*
Page: /qipai/dede/index.php
Error: 无法使用数据库
*/
?>
<?php  exit();
/*
Page: /qipai/dede/login.php?gotopage=%2Fqipai%2Fdede%2Findex.php
Error: 无法使用数据库
*/
?>
<?php  exit();
/*
Page: /qipai/dede/login.php?dopost=showad
Error: 无法使用数据库
*/
?>
